#!/bin/bash

function citc_name() {
  local wd=`pwd`
  IFS="/"; local arr=($wd); unset IFS;
  if [[ $wd == "/google/src/cloud/$USER"* ]] && [[ ${arr[5]} ]]; then
    printf ${arr[5]}
  fi
  unset IFS
}


hue_to_ansi256() {
  # Map hue (0-1536) to ANSI 256 color via OKLCH (L=0.68, C=0.16)
  # OKLCH ensures perceptually uniform brightness across all hues,
  # readable on both light and dark backgrounds.
  awk -v h="$1" 'BEGIN {
    pi = 3.14159265358979
    L = 0.55; C = 0.3
    H = h * 2 * pi / 1536

    # OKLCH -> OKLab
    a = C * cos(H); b = C * sin(H)

    # OKLab -> LMS (cube-root space)
    l_ = L + 0.3963377774*a + 0.2158037573*b
    m_ = L - 0.1055613458*a - 0.0638541728*b
    s_ = L - 0.0894841775*a - 1.2914855480*b

    # Cube
    l = l_*l_*l_; m = m_*m_*m_; s = s_*s_*s_

    # LMS -> linear sRGB
    r =  4.0767416621*l - 3.3077115913*m + 0.2309699292*s
    g = -1.2684380046*l + 2.6097574011*m - 0.3413193965*s
    b = -0.0041960863*l - 0.7034186147*m + 1.7076147010*s

    # Gamma (linear -> sRGB) + clamp
    r = r > 0 ? r^(1/2.2) : 0; if (r > 1) r = 1
    g = g > 0 ? g^(1/2.2) : 0; if (g > 1) g = 1
    b = b > 0 ? b^(1/2.2) : 0; if (b > 1) b = 1

    # sRGB -> ANSI 256 6x6x6 cube (index 16-231)
    printf "%d", 16 + 36*int(r*5+0.5) + 6*int(g*5+0.5) + int(b*5+0.5)
  }'
}

if [[ -e /usr/lib/git-core/git-sh-prompt ]]; then
  . /usr/lib/git-core/git-sh-prompt
  PS1_GIT="\$(__git_ps1)"
elif [[ -e /usr/share/git-core/contrib/completion/git-prompt.sh ]]; then
  . /usr/share/git-core/contrib/completion/git-prompt.sh
  PS1_GIT="\$(__git_ps1)"
fi

strToColor() {
  # Range 300-1450 maps to ~70°-340°: yellow→green→cyan→blue→purple
  # Avoids red/orange, reserving those hues for root.
  echo "$(hue_to_ansi256 $(( $(cksum <<< ${1} | cut -f 1 -d ' ') % 1150 + 300)))"
}

HOST_KEY_COLOR="$(strToColor $(hostname -s))"

prompt_command() {
    path="$(readlink -f .)"

    unset PROMPT_DIR_BASE_DESC

    while [[ "${path}" != / ]]; do
        if [[ -z "${path}" ]]; then
           PROMPT_DIR_BASE_DESC="bad-link"
           return
        fi
        PROMPT_DIR_BASE="$(basename ${path})"
        PROMPT_DIR_PATH="/$(realpath --relative-to="${path}" "$(readlink -f .)")"
        PROMPT_DIR_PATH="${PROMPT_DIR_PATH%./}"
        PROMPT_DIR_PATH="${PROMPT_DIR_PATH%/.}"

        if [[ -d "${path}/.git" ]]; then
          PROMPT_DIR_BASE_DESC="git:$(__git_ps1 '%s')"
          return
        fi

        if [[ "${path}" == "$HOME" ]]; then
          PROMPT_DIR_BASE="~"
          unset PROMPT_DIR_BASE_DESC
          return
        fi

        if [[ -d "${path}/.citc" && -d "${path}"/.jj ]]; then
          PROMPT_DIR_BASE="//depot"
          PROMPT_DIR_BASE_DESC="jj:$(citc_name ${path})"
          return
        fi
        if [[ -d "${path}/../.citc" && -d "${path}/../.jj" && "${path}" =~ .*/google3 ]]; then
          PROMPT_DIR_BASE="g3"
          PROMPT_DIR_BASE_DESC="jj:$(citc_name ${path})"
          return
        fi


        if [[ -d "${path}/.citc" && -d "${path}"/.hg ]]; then
          PROMPT_DIR_BASE="//depot"
          PROMPT_DIR_BASE_DESC="fig:$(citc_name ${path})"
          return
        fi
        if [[ -d "${path}/../.citc" && -d "${path}/../.hg" && "${path}" =~ .*/google3 ]]; then
          PROMPT_DIR_BASE="g3"
          PROMPT_DIR_BASE_DESC="fig:$(citc_name ${path})"
          return
        fi

        if [[ -d "${path}/.citc" ]]; then
          PROMPT_DIR_BASE="//depot"
          PROMPT_DIR_BASE_DESC="citc:$(citc_name ${path})"
          return
        fi
        if [[ -d "${path}/../.citc" &&  "${path}" =~ .*/google3 ]]; then
          PROMPT_DIR_BASE="g3"
          PROMPT_DIR_BASE_DESC="citc:$(citc_name ${path})"
          return
        fi

        if [[ "${path}" =~ ^/google/src/files/.*/depot$ ]]; then
          PROMPT_DIR_BASE="//depot"
          PROMPT_DIR_BASE_DESC="${path#/google/src/files/}"
          PROMPT_DIR_BASE_DESC="cl:${PROMPT_DIR_BASE_DESC%%/*}"
          return
        fi
        path="$(realpath -s "${path}/..")"
    done

    PROMPT_DIR_BASE=""
    PROMPT_DIR_PATH="$PWD"

}
export PROMPT_COMMAND="prompt_command"

PS1=""

if [[ $EUID -eq 0 ]]; then
  _USER_COLOR=196  # red
else
  _USER_COLOR=${HOST_KEY_COLOR}
fi

if [[ -n "$TMUX" ]]
then
  true
  # this is on tmux header so not needed here
elif [[ "$USER" == "codespace" ]]
then
  PS1+="\[$(tput bold)$(tput setaf ${_USER_COLOR})\]cs "
elif [[ "$TERM_PROGRAM" == "cider" ]]
then
  PS1+="\[$(tput bold)$(tput setaf ${_USER_COLOR})\]\h "
else
  PS1+="\[$(tput bold)$(tput setaf ${_USER_COLOR})\]\u@\h "
fi

PS1+="\[$(tput setaf 15)\]\${PROMPT_DIR_BASE_DESC+}\${PROMPT_DIR_BASE_DESC}\${PROMPT_DIR_BASE_DESC+ }"
PS1+="\[$(tput setaf 243)\]\${PROMPT_DIR_BASE}"
PS1+="\[$(tput setaf 15)\]\${PROMPT_DIR_PATH} "
PS1+="\[$(tput bold)$(tput setaf ${_USER_COLOR})\]\$\[$(tput sgr0)\] "
